apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    metallb.io/address-pool: ingress
spec:
  type: ClusterIP
  loadBalancerIP: 10.42.0.20
  externalTrafficPolicy: Cluster
  externalIPs:
    - 10.42.0.240
  selector:
    app.kubernetes.io/name: traefik
