apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shared-agents-view
  namespace: agents
subjects:
  - kind: Group
    name: group:thepeoples_dev_cluster_ops_devs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: shared-agents-view
