#!/usr/bin/env bash

set -euo pipefail

output_dir="${PUBLISH_PAGES_OUTPUT_DIR:-${GITHUB_PAGES_OUTPUT_DIR:-}}"
[[ -n "${output_dir}" ]] || {
  printf 'missing PUBLISH_PAGES_OUTPUT_DIR or GITHUB_PAGES_OUTPUT_DIR\n' >&2
  exit 1
}

mkdir -p "${output_dir}/results/charts" "${output_dir}/models"

cp "README.md" "${output_dir}/index.md"
cp "results/leaderboard.md" "${output_dir}/leaderboard.md"
cp -a "results/charts/." "${output_dir}/results/charts/"
cp "results/latest.json" "${output_dir}/results/latest.json"
cp "models/README.md" "${output_dir}/models/index.md"

cat >"${output_dir}/index.html" <<'EOF'
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>ORPT Bench</title>
  <style>
    body { font-family: system-ui, sans-serif; margin: 2rem auto; max-width: 60rem; padding: 0 1rem; line-height: 1.5; }
    h1 { margin-bottom: 0.5rem; }
    .grid { display: grid; gap: 1rem; grid-template-columns: repeat(auto-fit, minmax(14rem, 1fr)); margin: 2rem 0; }
    .card { border: 1px solid #d4d4d8; border-radius: 0.75rem; padding: 1rem; }
    a { color: #2563eb; text-decoration: none; }
    a:hover { text-decoration: underline; }
    ul { padding-left: 1.25rem; }
  </style>
</head>
<body>
  <h1>ORPT Bench</h1>
  <p>OpenCode Agentic Efficiency Benchmark publication generated by Gitea Actions.</p>
  <div class="grid">
    <div class="card">
      <h2>Benchmark Summary</h2>
      <ul>
        <li><a href="leaderboard.md">Leaderboard markdown</a></li>
        <li><a href="results/latest.json">Latest raw results</a></li>
        <li><a href="index.md">Repository README snapshot</a></li>
      </ul>
    </div>
    <div class="card">
      <h2>Charts</h2>
      <ul>
        <li><a href="results/charts/orpt.html">ORPT leaderboard</a></li>
        <li><a href="results/charts/success-rate.html">Success rate</a></li>
        <li><a href="results/charts/composite-score.html">Composite score</a></li>
      </ul>
    </div>
    <div class="card">
      <h2>Model Catalog</h2>
      <ul>
        <li><a href="models/index.md">Model catalog</a></li>
      </ul>
    </div>
  </div>
</body>
</html>
EOF
