apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |
    ports:
      web:
        forwardedHeaders:
          insecure: true
          trustedIPs:
            - 0.0.0.0/0
      websecure:
        forwardedHeaders:
          insecure: true
          trustedIPs:
            - 10.42.0.0/24
